### ISSUE TITLE
Make logging optional, or build in a default to the API 

### ISSUE THREAD

**Issue by ptsefton** [uws-eresearch/omeka-as-a-dora#4]
People using the API should be able to do so without having to set up logging in their script. Move the logger code from the xslx script to the api lib?

**Comment by TheKingOfThePotatoPeople** [comment]
I've added a default of None to the logger argument of the **init**() method of the OmekaClient class. If this comes in as None, then the OmekaClient will just throw each log message away. 

I also added create_*_logger methods to omekautils.py and had both the OmekaClient and the XLSX2Omeka script use them.
